/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as EconomyImport } from './routes/economy'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as VesselsIndexImport } from './routes/vessels/index'
import { Route as LocationsIndexImport } from './routes/locations/index'
import { Route as VesselsVesselIdImport } from './routes/vessels/$vesselId'
import { Route as LocationsCompanyIdImport } from './routes/locations/$companyId'

// Create/Update Routes

const EconomyRoute = EconomyImport.update({
  path: '/economy',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const VesselsIndexRoute = VesselsIndexImport.update({
  path: '/vessels/',
  getParentRoute: () => rootRoute,
} as any)

const LocationsIndexRoute = LocationsIndexImport.update({
  path: '/locations/',
  getParentRoute: () => rootRoute,
} as any)

const VesselsVesselIdRoute = VesselsVesselIdImport.update({
  path: '/vessels/$vesselId',
  getParentRoute: () => rootRoute,
} as any)

const LocationsCompanyIdRoute = LocationsCompanyIdImport.update({
  path: '/locations/$companyId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/economy': {
      id: '/economy'
      path: '/economy'
      fullPath: '/economy'
      preLoaderRoute: typeof EconomyImport
      parentRoute: typeof rootRoute
    }
    '/locations/$companyId': {
      id: '/locations/$companyId'
      path: '/locations/$companyId'
      fullPath: '/locations/$companyId'
      preLoaderRoute: typeof LocationsCompanyIdImport
      parentRoute: typeof rootRoute
    }
    '/vessels/$vesselId': {
      id: '/vessels/$vesselId'
      path: '/vessels/$vesselId'
      fullPath: '/vessels/$vesselId'
      preLoaderRoute: typeof VesselsVesselIdImport
      parentRoute: typeof rootRoute
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsIndexImport
      parentRoute: typeof rootRoute
    }
    '/vessels/': {
      id: '/vessels/'
      path: '/vessels'
      fullPath: '/vessels'
      preLoaderRoute: typeof VesselsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/economy': typeof EconomyRoute
  '/locations/$companyId': typeof LocationsCompanyIdRoute
  '/vessels/$vesselId': typeof VesselsVesselIdRoute
  '/locations': typeof LocationsIndexRoute
  '/vessels': typeof VesselsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/economy': typeof EconomyRoute
  '/locations/$companyId': typeof LocationsCompanyIdRoute
  '/vessels/$vesselId': typeof VesselsVesselIdRoute
  '/locations': typeof LocationsIndexRoute
  '/vessels': typeof VesselsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/economy': typeof EconomyRoute
  '/locations/$companyId': typeof LocationsCompanyIdRoute
  '/vessels/$vesselId': typeof VesselsVesselIdRoute
  '/locations/': typeof LocationsIndexRoute
  '/vessels/': typeof VesselsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/economy'
    | '/locations/$companyId'
    | '/vessels/$vesselId'
    | '/locations'
    | '/vessels'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/economy'
    | '/locations/$companyId'
    | '/vessels/$vesselId'
    | '/locations'
    | '/vessels'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/economy'
    | '/locations/$companyId'
    | '/vessels/$vesselId'
    | '/locations/'
    | '/vessels/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EconomyRoute: typeof EconomyRoute
  LocationsCompanyIdRoute: typeof LocationsCompanyIdRoute
  VesselsVesselIdRoute: typeof VesselsVesselIdRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  VesselsIndexRoute: typeof VesselsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EconomyRoute: EconomyRoute,
  LocationsCompanyIdRoute: LocationsCompanyIdRoute,
  VesselsVesselIdRoute: VesselsVesselIdRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  VesselsIndexRoute: VesselsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/economy",
        "/locations/$companyId",
        "/vessels/$vesselId",
        "/locations/",
        "/vessels/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/economy": {
      "filePath": "economy.tsx"
    },
    "/locations/$companyId": {
      "filePath": "locations/$companyId.tsx"
    },
    "/vessels/$vesselId": {
      "filePath": "vessels/$vesselId.tsx"
    },
    "/locations/": {
      "filePath": "locations/index.tsx"
    },
    "/vessels/": {
      "filePath": "vessels/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
